stages:
    - test
    - publish
    - prepare
    - build
    - deploy

include:
  - template: Security/SAST.gitlab-ci.yml
  - project: 'etus/devops/automation/deploy-automation'
    file: '/templates/npm/design-system.yml'
