declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BActionCard: typeof import('./components/BActionCard/BActionCard.vue')['default']
    BAlert: typeof import('./components/BAlert/BAlert.vue')['default']
    BAutoComplete: typeof import('./components/BAutoComplete/BAutoComplete.vue')['default']
    BAvatar: typeof import('./components/BAvatar/BAvatar.vue')['default']
    BBreadcrumb: typeof import('./components/BBreadcrumb/BBreadcrumb.vue')['default']
    BButton: typeof import('./components/BButton/BButton.vue')['default']
    BCard: typeof import('./components/BCard/BCard.vue')['default']
    BCheckbox: typeof import('./components/BCheckbox/BCheckbox.vue')['default']
    BCollapse: typeof import('./components/BCollapse/BCollapse.vue')['default']
    BColorPicker: typeof import('./components/BColorPicker/BColorPicker.vue')['default']
    BConfirm: typeof import('./components/BConfirm/BConfirm.vue')['default']
    BContentScreen: typeof import('./components/BContentScreen/BContentScreen.vue')['default']
    BCrop: typeof import('./components/BCrop/BCrop.vue')['default']
    BDate: typeof import('./components/BDate/BDate.vue')['default']
    BDateComparator: typeof import('./components/BDateComparator/BDateComparator.vue')['default']
    BDateComparatorFilter: typeof import('./components/BDateComparatorFilter/BDateComparatorFilter.vue')['default']
    BDateFilter: typeof import('./components/BDateFilter/BDateFilter.vue')['default']
    BDatePicker: typeof import('./components/BDatePicker/BDatePicker.vue')['default']
    BDialog: typeof import('./components/BDialog/BDialog.vue')['default']
    BDivider: typeof import('./components/BDivider/BDivider.vue')['default']
    BDropdown: typeof import('./components/BDropdown/BDropdown.vue')['default']
    BExpandableContainer: typeof import('./components/BExpandableContainer/BExpandableContainer.vue')['default']
    BFilter: typeof import('./components/BFilter/BFilter.vue')['default']
    BFloatCard: typeof import('./components/BFloatCard/BFloatCard.vue')['default']
    BGroup: typeof import('./components/BGroup/BGroup.vue')['default']
    BHistory: typeof import('./components/BHistory/BHistory.vue')['default']
    BIcon: typeof import('./components/BIcon/BIcon.vue')['default']
    BIconCard: typeof import('./components/BIconCard/BIconCard.vue')['default']
    BInput: typeof import('./components/BInput/BInput.vue')['default']
    BMenu: typeof import('./components/BMenu/BMenu.vue')['default']
    BMetricCard: typeof import('./components/BMetricCard/BMetricCard.vue')['default']
    BMultiSelect: typeof import('./components/BMultiSelect/BMultiSelect.vue')['default']
    BNavbar: typeof import('./components/BNavbar/BNavbar.vue')['default']
    BPagination: typeof import('./components/BPagination/BPagination.vue')['default']
    BProfile: typeof import('./components/BProfile/BProfile.vue')['default']
    BProgressBar: typeof import('./components/BProgressBar/BProgressBar.vue')['default']
    BRadio: typeof import('./components/BRadio/BRadio.vue')['default']
    BRadioButton: typeof import('./components/BRadioButton/BRadioButton.vue')['default']
    BRangeSlider: typeof import('./components/BRangeSlider/BRangeSlider.vue')['default']
    BRoundButton: typeof import('./components/BRoundButton/BRoundButton.vue')['default']
    BRoundMenu: typeof import('./components/BRoundMenu/BRoundMenu.vue')['default']
    BSelect: typeof import('./components/BSelect/BSelect.vue')['default']
    BSelectContainer: typeof import('./components/BSelectContainer/BSelectContainer.vue')['default']
    BSidebar: typeof import('./components/BSidebar/BSidebar.vue')['default']
    BSideMenu: typeof import('./components/BSideMenu/BSideMenu.vue')['default']
    BSkeleton: typeof import('./components/BSkeleton/BSkeleton.vue')['default']
    BSlider: typeof import('./components/BSlider/BSlider.vue')['default']
    BSmartSelect: typeof import('./components/BSmartSelect/BSmartSelect.vue')['default']
    BSpinner: typeof import('./components/BSpinner/BSpinner.vue')['default']
    BStepOption: typeof import('./components/BStepOption/BStepOption.vue')['default']
    BStepper: typeof import('./components/BStepper/BStepper.vue')['default']
    BTab: typeof import('./components/BTab/BTab.vue')['default']
    BTable: typeof import('./components/BTable/BTable.vue')['default']
    BTag: typeof import('./components/BTag/BTag.vue')['default']
    BTagInput: typeof import('./components/BTagInput/BTagInput.vue')['default']
    BTagSelect: typeof import('./components/BTagSelect/BTagSelect.vue')['default']
    BToast: typeof import('./components/BToast/BToast.vue')['default']
    BToggle: typeof import('./components/BToggle/BToggle.vue')['default']
    BTooltip: typeof import('./components/BTooltip/BTooltip.vue')['default']
  }
}

export {}
