declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionCard: typeof import('./components/ActionCard/ActionCard.vue')['default']
    Alert: typeof import('./components/Alert/Alert.vue')['default']
    AutoComplete: typeof import('./components/AutoComplete/AutoComplete.vue')['default']
    Avatar: typeof import('./components/Avatar/Avatar.vue')['default']
    Breadcrumb: typeof import('./components/Breadcrumb/Breadcrumb.vue')['default']
    Button: typeof import('./components/Button/Button.vue')['default']
    Card: typeof import('./components/Card/Card.vue')['default']
    Checkbox: typeof import('./components/Checkbox/Checkbox.vue')['default']
    Collapse: typeof import('./components/Collapse/Collapse.vue')['default']
    ColorPicker: typeof import('./components/ColorPicker/ColorPicker.vue')['default']
    Confirm: typeof import('./components/Confirm/Confirm.vue')['default']
    ContentScreen: typeof import('./components/ContentScreen/ContentScreen.vue')['default']
    Crop: typeof import('./components/Crop/Crop.vue')['default']
    Date: typeof import('./components/Date/Date.vue')['default']
    DateComparator: typeof import('./components/DateComparator/DateComparator.vue')['default']
    DateComparatorFilter: typeof import('./components/DateComparatorFilter/DateComparatorFilter.vue')['default']
    DateFilter: typeof import('./components/DateFilter/DateFilter.vue')['default']
    DatePicker: typeof import('./components/DatePicker/DatePicker.vue')['default']
    Dialog: typeof import('./components/Dialog/Dialog.vue')['default']
    Divider: typeof import('./components/Divider/Divider.vue')['default']
    Dropdown: typeof import('./components/Dropdown/Dropdown.vue')['default']
    ExpandableContainer: typeof import('./components/ExpandableContainer/ExpandableContainer.vue')['default']
    FileUpload: typeof import('./components/FileUpload/FileUpload.vue')['default']
    Filter: typeof import('./components/Filter/Filter.vue')['default']
    FloatCard: typeof import('./components/FloatCard/FloatCard.vue')['default']
    Group: typeof import('./components/Group/Group.vue')['default']
    History: typeof import('./components/History/History.vue')['default']
    Icon: typeof import('./components/Icon/Icon.vue')['default']
    IconCard: typeof import('./components/IconCard/IconCard.vue')['default']
    Input: typeof import('./components/Input/Input.vue')['default']
    Menu: typeof import('./components/Menu/Menu.vue')['default']
    MetricCard: typeof import('./components/MetricCard/MetricCard.vue')['default']
    MultiSelect: typeof import('./components/MultiSelect/MultiSelect.vue')['default']
    Navbar: typeof import('./components/Navbar/Navbar.vue')['default']
    Pagination: typeof import('./components/Pagination/Pagination.vue')['default']
    Profile: typeof import('./components/Profile/Profile.vue')['default']
    ProgressBar: typeof import('./components/ProgressBar/ProgressBar.vue')['default']
    Radio: typeof import('./components/Radio/Radio.vue')['default']
    RangeSlider: typeof import('./components/RangeSlider/RangeSlider.vue')['default']
    RoundButton: typeof import('./components/RoundButton/RoundButton.vue')['default']
    RoundMenu: typeof import('./components/RoundMenu/RoundMenu.vue')['default']
    Select: typeof import('./components/Select/Select.vue')['default']
    SelectContainer: typeof import('./components/SelectContainer/SelectContainer.vue')['default']
    Sidebar: typeof import('./components/Sidebar/Sidebar.vue')['default']
    SideMenu: typeof import('./components/SideMenu/SideMenu.vue')['default']
    Skeleton: typeof import('./components/Skeleton/Skeleton.vue')['default']
    Slider: typeof import('./components/Slider/Slider.vue')['default']
    SmartSelect: typeof import('./components/SmartSelect/SmartSelect.vue')['default']
    Spinner: typeof import('./components/Spinner/Spinner.vue')['default']
    StepOption: typeof import('./components/StepOption/StepOption.vue')['default']
    Stepper: typeof import('./components/Stepper/Stepper.vue')['default']
    Switch: typeof import('./components/Switch/Switch.vue')['default']
    Tab: typeof import('./components/Tab/Tab.vue')['default']
    Table: typeof import('./components/Table/Table.vue')['default']
    Tag: typeof import('./components/Tag/Tag.vue')['default']
    TagInput: typeof import('./components/TagInput/TagInput.vue')['default']
    TagSelect: typeof import('./components/TagSelect/TagSelect.vue')['default']
    Textarea: typeof import('./components/Textarea/Textarea.vue')['default']
    Toast: typeof import('./components/Toast/Toast.vue')['default']
    Toggle: typeof import('./components/Toggle/Toggle.vue')['default']
    Tooltip: typeof import('./components/Tooltip/Tooltip.vue')['default']
  }
}

export {}
